import type { Artisan, Artwork } from "../types";

/** Static archive registry: mirrors the seeded dataset so the fingerprinted
 *  works, their plates and the artisan records stay viewable even when the
 *  API is unreachable. Plates resolve via ``plateUrlFor`` to bundled media. */
export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: "mock-artwork-01",
    heritage_id: "VR-OD-PAT-2026-000001",
    title: "Dashavatara Patta",
    dimensions: "24 x 18 in",
    medium: "Cotton Patta with Tamarind seed adhesive, mineral pigments, lacquer seal",
    creation_year: 2026,
    artisan_id: "mock-artisan-01",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 3505.7,
    primary_image_url: "/media/artworks/artwork-01.jpg",
    created_at: "",
    artisan_name: "Gopinath Moharana",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "master_verified",
  },
  {
    id: "mock-artwork-02",
    heritage_id: "VR-OD-PAT-2026-000002",
    title: "Krishna Leela Kriya",
    dimensions: "12 x 9 in",
    medium: "Cotton Patta with Tamarind seed adhesive, mineral pigments",
    creation_year: 2024,
    artisan_id: "mock-artisan-01",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 15783.9,
    primary_image_url: "/media/artworks/artwork-02.jpg",
    created_at: "",
    artisan_name: "Gopinath Moharana",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "master_verified",
  },
  {
    id: "mock-artwork-03",
    heritage_id: "VR-OD-PAT-2026-000003",
    title: "Nabagunjara — Cosmic Form of Krishna",
    dimensions: "30 x 22 in",
    medium: "Cotton Patta with chalk & conch-shell ground, mineral pigments",
    creation_year: 2025,
    artisan_id: "mock-artisan-02",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 5678.7,
    primary_image_url: "/media/artworks/artwork-03.jpg",
    created_at: "",
    artisan_name: "Shyamsundar Moharana",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "field_verified",
  },
  {
    id: "mock-artwork-04",
    heritage_id: "VR-OD-PAT-2026-000004",
    title: "Radha-Krishna in the Grove",
    dimensions: "18 x 14 in",
    medium: "Cotton Patta with Tamarind seed adhesive, mineral pigments",
    creation_year: 2026,
    artisan_id: "mock-artisan-03",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 49094.8,
    primary_image_url: "/media/artworks/artwork-04.jpg",
    created_at: "",
    artisan_name: "Aditya Moharana",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "field_verified",
  },
  {
    id: "mock-artwork-05",
    heritage_id: "VR-OD-PAT-2026-000005",
    title: "Matsya Avatar on Patta",
    dimensions: "15 x 11 in",
    medium: "Cotton Patta with mineral pigments",
    creation_year: 2023,
    artisan_id: "mock-artisan-03",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 15364.2,
    primary_image_url: "/media/artworks/artwork-05.jpg",
    created_at: "",
    artisan_name: "Aditya Moharana",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "pending",
  },
  {
    id: "mock-artwork-06",
    heritage_id: "VR-OD-PAT-2026-000006",
    title: "Vamana Avatar — Three Strides",
    dimensions: "20 x 16 in",
    medium: "Cotton Patta with chalk ground, mineral pigments",
    creation_year: 2025,
    artisan_id: "mock-artisan-04",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 15502.9,
    primary_image_url: "/media/artworks/artwork-06.jpg",
    created_at: "",
    artisan_name: "Kanchana Sahoo",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "field_verified",
  },
  {
    id: "mock-artwork-07",
    heritage_id: "VR-OD-PAT-2026-000007",
    title: "Kalika Pattachitra",
    dimensions: "16 x 12 in",
    medium: "Cotton Patta with mineral pigments",
    creation_year: 2024,
    artisan_id: "mock-artisan-05",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 950.4,
    primary_image_url: "/media/artworks/artwork-07.jpg",
    created_at: "",
    artisan_name: "Sunita Sahoo",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "pending",
  },
  {
    id: "mock-artwork-08",
    heritage_id: "VR-OD-PAT-2026-000008",
    title: "Jagannath Trinity on Patta",
    dimensions: "24 x 18 in",
    medium: "Cotton Patta with chalk & conch-shell ground, mineral pigments",
    creation_year: 2026,
    artisan_id: "mock-artisan-06",
    phash_signature: null,
    dhash_signature: null,
    blur_score: 16923.7,
    primary_image_url: "/media/artworks/artwork-08.jpg",
    created_at: "",
    artisan_name: "Devraj Sahoo",
    tradition_title: "Odisha Pattachitra",
    origin_state: "Odisha",
    verification_status: "master_verified",
  },
];

export const MOCK_ARTISANS: Artisan[] = [
  {
    id: "mock-artisan-01",
    full_name: "Gopinath Moharana",
    pehchan_card_id: "PCH-OD-11021",
    biography: "Patriarch of a six-generation chitrakar family of Raghurajpur and keeper of the traditional iconometric grammar — master outliner of the household.",
    generation_number: 1,
    parent_artisan_id: null,
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "master_verified",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
  {
    id: "mock-artisan-02",
    full_name: "Shyamsundar Moharana",
    pehchan_card_id: "PCH-OD-11022",
    biography: "Fifth generation carrier of the craft; leads the family workshop for large ritual pattas, teaching in the traditional guru-shishya manner.",
    generation_number: 2,
    parent_artisan_id: "mock-artisan-01",
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "master_verified",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
  {
    id: "mock-artisan-03",
    full_name: "Aditya Moharana",
    pehchan_card_id: "PCH-OD-11023",
    biography: "Fourth generation in the workshop; trained at the family bench, paints in the strict traditional palette and records his grandmother's oral stories.",
    generation_number: 3,
    parent_artisan_id: "mock-artisan-02",
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "field_verified",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
  {
    id: "mock-artisan-04",
    full_name: "Kanchana Sahoo",
    pehchan_card_id: "PCH-OD-11031",
    biography: "One of the oldest patta-painting households of the village; celebrated for miniature palm-leaf-style pattas and for teaching the women's circle of Raghurajpur.",
    generation_number: 1,
    parent_artisan_id: null,
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "master_verified",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
  {
    id: "mock-artisan-05",
    full_name: "Sunita Sahoo",
    pehchan_card_id: "PCH-OD-11032",
    biography: "Daughter of Kanchana; paints the Krishna Leela cycle and tiger faces of the festival masks, coordinating the women's cooperative's export documentation.",
    generation_number: 2,
    parent_artisan_id: "mock-artisan-04",
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "field_verified",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
  {
    id: "mock-artisan-06",
    full_name: "Devraj Sahoo",
    pehchan_card_id: "PCH-OD-11033",
    biography: "Youngest painter of the Sahoo household; learning the iconometric grammar under his mother and the first to have his work fingerprinted for the digital archive.",
    generation_number: 3,
    parent_artisan_id: "mock-artisan-05",
    region_id: "mock-region-raghurajpur",
    primary_tradition_id: "mock-tradition-pattachitra",
    verification_status: "pending",
    profile_image_url: null,
    created_at: "",
    region_name: "Raghurajpur, Puri, Odisha",
    tradition_title: "Odisha Pattachitra",
  },
];

export function mockArtworkByHeritageId(heritageId: string): Artwork | null {
  return MOCK_ARTWORKS.find((a) => a.heritage_id === heritageId) ?? null;
}

export function mockArtisanById(id: string): Artisan | null {
  return MOCK_ARTISANS.find((a) => a.id === id) ?? null;
}